// <auto-generated />
using FirstApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240501145915_add-data")]
    partial class adddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FirstApp.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Course Name");

                    b.Property<decimal>("Price")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseName = "Mathematics",
                            Price = 1000.00m
                        },
                        new
                        {
                            Id = 2,
                            CourseName = "Physics",
                            Price = 2000.00m
                        },
                        new
                        {
                            Id = 3,
                            CourseName = "Chemistry",
                            Price = 1500.00m
                        },
                        new
                        {
                            Id = 4,
                            CourseName = "Biology",
                            Price = 1200.00m
                        },
                        new
                        {
                            Id = 5,
                            CourseName = "Computer Science",
                            Price = 3000.00m
                        });
                });

            modelBuilder.Entity("FirstApp.Entities.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("officeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("officeId")
                        .IsUnique();

                    b.ToTable("Instructors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ahmed Abdullah",
                            officeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Yasmeen Mohammed",
                            officeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Khalid Hassan",
                            officeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Nadia Ali",
                            officeId = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Omar Ibrahim",
                            officeId = 5
                        });
                });

            modelBuilder.Entity("FirstApp.Entities.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("OfficeLocation")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Offices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Off_05",
                            OfficeLocation = "building A"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Off_12",
                            OfficeLocation = "building B"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Off_32",
                            OfficeLocation = "Adminstration"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Off_44",
                            OfficeLocation = "IT Department"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Off_43",
                            OfficeLocation = "IT Department"
                        });
                });

            modelBuilder.Entity("FirstApp.Entities.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Sections", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            InstructorId = 1,
                            SectionName = "S_MA1"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            InstructorId = 2,
                            SectionName = "S_MA2"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 2,
                            InstructorId = 1,
                            SectionName = "S_PH1"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            InstructorId = 3,
                            SectionName = "S_PH2"
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 3,
                            InstructorId = 2,
                            SectionName = "S_CH1"
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 3,
                            InstructorId = 3,
                            SectionName = "S_CH2"
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 4,
                            InstructorId = 4,
                            SectionName = "S_BI1"
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 4,
                            InstructorId = 5,
                            SectionName = "S_BI2"
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 5,
                            InstructorId = 4,
                            SectionName = "S_CS1"
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 5,
                            InstructorId = 5,
                            SectionName = "S_CS2"
                        },
                        new
                        {
                            Id = 11,
                            CourseId = 5,
                            InstructorId = 4,
                            SectionName = "S_CS3"
                        });
                });

            modelBuilder.Entity("FirstApp.Entities.Instructor", b =>
                {
                    b.HasOne("FirstApp.Entities.Office", "Office")
                        .WithOne("Instructor")
                        .HasForeignKey("FirstApp.Entities.Instructor", "officeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("FirstApp.Entities.Section", b =>
                {
                    b.HasOne("FirstApp.Entities.Course", "Course")
                        .WithMany("Sections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FirstApp.Entities.Instructor", "Instructor")
                        .WithMany("Sections")
                        .HasForeignKey("InstructorId");

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("FirstApp.Entities.Course", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("FirstApp.Entities.Instructor", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("FirstApp.Entities.Office", b =>
                {
                    b.Navigation("Instructor")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
